"""Adding d3 graph column

Revision ID: b995a9f0549d
Revises: 61f5e253be29
Create Date: 2025-10-26 19:46:28.800785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b995a9f0549d'
down_revision = '61f5e253be29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_policy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policyJSON_d3', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_policy', schema=None) as batch_op:
        batch_op.drop_column('policyJSON_d3')

    # ### end Alembic commands ###
